### PR TITLE
easy_permutation.cpp

### PR DESCRIPTION
**Pull request by Shreya-Lu**
Added solution for LTime111 @ Easy Permutation

### CODE REVIEW

**Review by swoyam2609 — CHANGES_REQUESTED** [review]
The code for this problem is already available in the directory, can you mention what are the changes and other features that you've added in this code

**Comment by Shreya-Lu** [comment]
I have done the possible changes

**Comment by swoyam2609** [comment]
> I have done the possible changes

I would like to know the differences between your code and the code that is existing in the current directory

**Comment by Shreya-Lu** [comment]
There is no difference in the output but the approach is different. The existing code uses a for loop within a while loop but the code submitted by me has nested while loop.

**Comment by swoyam2609** [comment]
Thanks for your contribution, keep contributing....

**Comment by Shreya-Lu** [comment]
Even though my PR has been merged, why is not reflected in my Hacktober profile?

**Pull request merged**
