### PR TITLE
Added

### PR DESCRIPTION
**Pull request by dp-lisin11**

### CODE REVIEW

**Review by swoyam2609 — CHANGES_REQUESTED** [review]
What was the previous PR if these are the codes for JULY221D

**Comment by dp-lisin11** [comment]
These ones are for JUNE221D

**Comment by dp-lisin11** [comment]
Previous was for July221D

**Comment by swoyam2609** [comment]
Sorry @dp-lisin11 
But so frequent pull requests to the same repository will lead to a temporary/permanent ban of your account from HacktoberFest or can cause exclusion of this repository from HacktoberFest
Due to the same, We can't accept your pull request. I hope you'll understand the issue, but in the meanwhile, we encourage you to look out for other repositories and contribute to the same.


Happy Contributing,
With regards,
Swoyam Siddharth
@swoyam2609

**Comment by dp-lisin11** [comment]
Sure

**Pull request closed without merging**
